### ISSUE TITLE
Adding a API Fct. for strings

### ISSUE THREAD

**Issue by Voetzl** [AlexKOrSo/Uebung-Morsezeichen#1]
`#include <avr/io.h>
#include <Arduino.h>

#ifndef F_CPU
#define F_CPU 16000000UL
#endif

extern "C" {
    #include "morse.h"
}

#define LED PORTB5
Morse MorseConfig;

int main(void){

  Serial.begin(9600); //Zur Nutzung fürs Debugging

  DDRB |= (1 << DDB5); //Eingebaute LED an PIN 13 wird die Morse-Leuchte

  char string[] = "helloworld"; //Das, was ausgegeben werden soll, hier ändern! Aber nur Kleinbuchstaben und Zahlen, keine Umlaute, kein ß.
  //int breakcounter = 0;

  for(int i = 0; i < 10; i++){ //Maximal 1000 Zeichen ausgeben
    
  

    int stelle;

    if (string[i] >= 97 && string[i] <= 122) {
      stelle = string[i];
    }/*
    if (string[i] >= 90 && string[i] <= 65){
      stelle = string[i];
    }*/
    else if (string[i] >= 48 && string[i] <= 57){
      stelle = string[i];
    }
    else{
      stelle = 0;
      /*_delay_ms(200); //Pause zu nächstem Wort
      breakcounter ++;
      if (breakcounter >= 2){
        break;
      }*/
    }

    Serial.println("Stelle:");
    Serial.println(i); //Bestätigung dass Auswahlverfahren geglückt ist

    char letter = stelle;   
    
      MorseChar(&letter);
      //breakcounter = 0;
  
  
    //ACHTUNG: Breakcounter zurücksetzen!!!
  }
}`

**Comment by Voetzl** [comment]
The issue:
LED blinkt (vermutlich) 1000 mal gleichmäßig.

**Comment by AlexKOrSo** [comment]
Die aktuelle API-Fkt übernimmt nur einzelne Chars, könnte man um eine entsprechende FKT für Strings erweitern.

https://github.com/AlexKOrSo/Uebung-Morsezeichen/blob/989081c6150788ae9e8f43ae03960cbae9a6170e/lib/Morse/morse.c#L84-L107

**Comment by AlexKOrSo** [comment]
Ich habe für die Implementierung einen Branch erstellt

**Comment by Voetzl** [comment]
Ansatz bisher: String in einzelne chars umwandeln und die dann wie bisher an die morse.c übergeben. 
Issue: Klappt nicht
